### ISSUE TITLE
Creating Exp using another Exp

### ISSUE THREAD

**Issue by mobab** [pellierd/pddl4j#1]
```
Exp conditions = domain.getOperators().get(0).getPreconditions();
Exp conditions_copy = new Exp(conditions);
```

when the conditions are literals there is no problem, and the copy is correct
```
    :condition (and 
		    (at start (in ?p ?l1))
                    (at start (haspower ?p))
                )
```
1- But the problem shows up when one of the conditions has numbers 
```
    :condition (and 
		    (at start (in ?p ?l1))
		    (at start (< (money ?p) 50))
                )
```
**The copy will be (at start (< (money ?p) null))**
2- similarly there is a problem when the condition contains 
```
    :condition (and 
		    (at start (in ?p ?l1))
		    (at start (< (money ?p) (somemoney)))
                )
```
note: (somemoney) is a fluent defined in domain.pddl as 
  (:functions 
	..
	..
        ..
	(somemoney)
  )
and assigned a value in the problem.pddl
 (:init
       ......
       .....
	(= (somemoney) 50)
 )

[domain.txt](https://github.com/pellierd/pddl4j/files/109920/domain.txt)
[problem.txt](https://github.com/pellierd/pddl4j/files/109919/problem.txt)

**Comment by mobab** [comment]
Suggested solution:
adding the following condition to the constructor public Exp(final Exp other) {.....} int the Class Exp.java
```
		if(this.connective.equals(Connective.NUMBER))
		{
			this.value= other.getValue();
		}

```

**Comment by pellierd** [comment]
The bug is fixed.
