### ISSUE TITLE
Apparent poor performance

### ISSUE THREAD

**Issue by antbono** [pellierd/pddl4j#105]
Hi everyone!

I am trying to follow the tutorial to get started with this library.

When I run any example I get always the same following warning in the console
```

WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
parsing domain file "domain.pddl" done successfully
parsing problem file "p03.pddl" done successfully
# WARNING: Unable to get Instrumentation. Dynamic Attach failed. You may add this JAR as -javaagent manually, or supply -Djdk.attach.allowAttachSelf
# WARNING: Unable to attach Serviceability Agent. You can try again with escalated privileges. Two options: a) use -Djol.tryWithSudo=true to try with sudo; b) echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope
```
I tried both with openjdk 11 and oracle jdk 22. At the moment the solver take a very long time also with a 'simple' problem like

`src/test/resources/benchmarks/pddl/ipc2002/depots/strips-automatic/p05.pddl`

Is that normal? 

Thank you very much for your attention

**Comment by pellierd** [comment]
Yes it is normal. 

To get the memory size of the object with java you need to add a java agent. 

This warning has no impact on the solutions found. 

if you want to removed the warning add to the commande line "-javaagent pddl4-xxx.jar"

**Comment by antbono** [comment]
Thank you @pellierd. So there is no way to improve the time performance, right?

**Comment by pellierd** [comment]
The calls to the refection methods (that can have an impact on time )are done once at the end of the search of a solution plan to get size information about data structures used during search. Thus, the impact is very limited. To speed up the search, unfortunately you have to develop your own heuristics and your own planner.

**Comment by antbono** [comment]
Thank you @pellierd! :)
