### ISSUE TITLE
Help -- solution output

### ISSUE THREAD

**Issue by antbono** [pellierd/pddl4j#106]
Hi everyone!

I'd like to have the sequential plan saved in a file like `solution.txt` in addition to see it on the terminal.

Could it be possible to obtain it by running a planner via command line? 

Thank you!

**Comment by antbono** [comment]
I found a quite simplistic solution by adding a fileWriter object in AbstractPlanner.java
You can find the modified class in the attachement. What do you think?

Thanks! :D

[AbstractPlanner.java.txt](https://github.com/pellierd/pddl4j/files/11412917/AbstractPlanner.java.txt)

**Comment by pellierd** [comment]
to redirect the output of the command line just use: > output.pddl

**Comment by antbono** [comment]
Thank you, @pellierd !
Your suggestion is useful, but I'd prefer to have only the plan solution in the file and not the entire terminal output. For this reason in the modified AbstractPlanner.java I used the method pb.toString(plan).
It would be nice to have a terminal option when calling pddl4j to choose the destination path of solution plan file (in my code it is saved in the directory where pddl4j is called).

Thank you again for your time and consideration

**Comment by pellierd** [comment]
No more question.

**Comment by antbono** [comment]
Hi @pellierd !
Sorry for the late reply... 
Your suggestion is fine but I'd prefer to have only the plan as text and not the entire terminal output with additional info
