### ISSUE TITLE
Support for action costs?

### ISSUE THREAD

**Issue by rumster** [pellierd/pddl4j#11]
Dear Demien,

Thanks for making PDDL4J available.
In my project, the problems are relatively small so the planner is able to solve them fast enough. However, it is hard to control the quality of the solution without associating costs with actions.
Would you consider adding support for actions costs? Even constant values could be helpful.

Thanks and best regards,
Roman

**Comment by pellierd** [comment]
For the moment I have no ressource to implement this enhancement. 
If you have time fill free to propose this enhancement to PDDL4J.

Best,

Damien

**Comment by pellierd** [comment]
We implement cost action but for the moment the code is not public.

If you are interested, contact me.

**Comment by rumster** [comment]
Thanks for thinking of me Demien,
My research has shifted away from traditional planning since then. I may need this feature in the future though.
Roman

**Comment by Byssis** [comment]
Hi!
Is action cost supported in the current version?
Albin

**Comment by ehermellin** [comment]
Hi!
Action cost is not in open source access for the moment. May be in the future. Only the parser layer of the library is full compatible with PDDL 3.1. Thus for the moment you can not use pddl4j to solve your problems.

Best regards, 

Emmanuel.

**Comment by ehermellin** [comment]
Hi!
Action cost is now release in PDDL4J v3.8 and is supported in parser layer, encoding layer and solving layer.
Best regards,
Emmanuel.
