### ISSUE TITLE
Incorrect format displayed by the parsedProblem.toString function for HDDL domains

### ISSUE THREAD

**Issue by gaspard-quenard** [pellierd/pddl4j#110]
I am trying to modify a HDDL domain with pddl4j and rewrite the new domain modified in a file. I am using the binary pddl4j-4.0.0.jar for my code. 

To do this, the general structure  of my code is as follow:

```java
 // Parses the domain and the problem files.
 final Parser parser = new Parser();
 final DefaultParsedProblem parsedProblem = parser.parse(<domain>,<problem>);

// Modify the domain 
// ...
// 

 // Write the new domain (bit of a hack here, the method toPDDLDomainString is private, so to access an equivalent we need to tell that the problem is null)
 parsedProblem.setProblemName(null);
 String newDomainFile = parsedProblem.toString();
```

The problem is that the function parsedProblem.toString() produce a incorrect format for a domain file:

### Task index is not written in the correct place:

For example if I run the function parsedProblem.toString() for the domain: ipc2020/Blockworld-GTOHP/domain.hddl, it gives me:

```code
;...

(:method m1_do_put_on
  :parameters (?x - BLOCK ?y - BLOCK)
  :task (do_put_on ?x ?y)
  :precondition
  (and (handempty ))
  :ordered-subtasks
  (and (do_clear t1 (?x)
    (do_clear t2 (?y)
    (do_on_table t3 (?y)
    (do_move t4 (?x ?y))
)

;...
```

but the task index should be before the subtask name, so it should be instead:

```code
(:method m1_do_put_on
  :parameters (?x - BLOCK ?y - BLOCK)
  :task (do_put_on ?x ?y)
  :precondition
  (and (handempty ))
  :ordered-subtasks
  (and (t1 (do_clear ?x))
    (t2 (do_clear ?y))
    (t3 (do_on_table ?y))
    (t4 (do_move ?x ?y))
)
```

### Bracket problem

In the same example, there is also a bracket problem (there should not be an open bracket before the parameters of each subtask, and this bracket is never closed).

### Case problem: 

Once the domain is parsed, all the object types are written in upper case. Would it be possible to have an option in the parser to keep the same case as those in the domain ? 

Would it be possible to update the method parsedProblem.toString to take into account those modification ? Thanks

**Comment by pellierd** [comment]
The task index not written in the correct place and the bracket problem are now solved in the devel branch.

For the problem of the case, please refer to issue #99. To have a parser case sensitive, you have just change the option in the file [Lexer.jj](https://github.com/pellierd/pddl4j/blob/master/src/main/java/fr/uga/pddl4j/parser/lexer/Lexer.jj) ligne 22 
`IGNORE_CASE=true;` by `  IGNORE_CASE=false;` and rebuild the library.

**Comment by pellierd** [comment]
It should be solved in the devel branch.

**Comment by pellierd** [comment]
It should be solved in the devel branch.
