### ISSUE TITLE
no main manifest attribute

### ISSUE THREAD

**Issue by Lucy4621** [pellierd/pddl4j#115]
![Capture](https://github.com/pellierd/pddl4j/assets/163475162/2aee44f7-706e-4468-819c-1d6e46e58481)
###  **no main manifest attribute**

please can you help me here !!

**Comment by pellierd** [comment]
The document is available here: 
http://pddl4j.imag.fr/running_planners_from_command_line.html#hsp-heuristic-search-planner

**Comment by Lucy4621** [comment]
r
