### ISSUE TITLE
Does pddl4j support the :domain-axiom requirement?

### ISSUE THREAD

**Issue by nvannaprathip** [pellierd/pddl4j#12]
I tested and  found that the parser cannot recognize the requirement **:domain-axiom** (which is the feature I need to use). The question is, does pddl4j support this **:domain-axiom** requirement?

Thanks, 

N.

**Comment by pellierd** [comment]
The parser accepts axiom declaration. The requirement to use is **:derived-predicates**. Please refer to the PDDL3.1 BNF available at http://www.plg.inf.uc3m.es/ipc2011-deterministic/attachments/OtherContributions/kovacs-pddl-3.1-2011.pdf

DP

**Comment by nvannaprathip** [comment]
Thanks.
