### ISSUE TITLE
Question about the use of negative literal for the derived predicate

### ISSUE THREAD

**Issue by nvannaprathip** [pellierd/pddl4j#13]
I test the (:derived ) and found that only positive literal is allowed for derived predicate. In my case, I would like to derive the negative predicates  like the following example

`(:derive (not (predicate_x) )   (predicate_y) ) `

Is there any other way to meet this need? 

Thanks,

**Comment by pellierd** [comment]
According to the PDDL 3.1 the specification of negative predicates is not allowed. 
A way to express negative predicate is to create a new predicate "not_predicate".
