### ISSUE TITLE
Question about the variables declared in derived predicates 

### ISSUE THREAD

**Issue by nvannaprathip** [pellierd/pddl4j#14]
I tested with the following example and the parser say that ?x is undefined. 
   ```
(:derived  (TEST_5 ?z)  (TEST_4 ?x ?y)    )
```
The question is the number of variables declared in derived predicate (TEST_5 ?z) must be exactly the same as variables used in the basic predicate (TEST_4 ?x ?y) ? 

I am very new to PDDL, I tried to apply the :derived in my project. And I saw the example from [http://www.sciencedirect.com/science/article/pii/S0004370205000810](url) and test with your parser. The test result is not as I thought. However, please help advising that. Thank you very much.

**Comment by pellierd** [comment]
All the variable used in the body of the derived predicates have to be bound.
