### ISSUE TITLE
Question about old version of code

### ISSUE THREAD

**Issue by JenniferBuehler** [pellierd/pddl4j#17]
Hello Damien,

A couple of years ago I used an older version of your PDDL4J code for my PhD. I had implemented a variation of the SAPA planner with the help of your code. The planner required online action instantiation (see [this paper](http://www.aaai.org/ocs/index.php/AAAI/AAAI14/paper/viewFile/8476/8645)). For this, I found the ``Exp`` structures along with ``Substitution`` very useful.

I see that the code provided here has since changed quite a bit. Back then I had used the version cloned from @gerryai in [this PDDL4J repository](https://github.com/gerryai/PDDL4J). I had to do a few modifications and fixed a few minor things to this code.

Now I am re-working my planner code in order to get ready for publishing it. For this, I will need to have my modified version of your old PDDL4J code published somewhere. Unfortunately I don't have the time to change to the new pddl4j structures in this repository (also I can't find Substitution any more), and would just like to use what I already have.

To the point: I would like to know if you have any preferences in terms of how to go about this, since it is a clone of an old PDDL4J version. I have put up my changes in [my fork of @gerryai's repository](https://github.com/JenniferBuehler/PDDL4J/tree/pddl4j_buehler) (branch pddl4j_buehler). There is a [file describing my modifications](https://github.com/JenniferBuehler/PDDL4J/blob/pddl4j_buehler/MODIFICATIONS.md) in there. A few things from the old code have been discarded, and some new things have been added (for example parsing of PDDL3.1 is done with the help of ANTLR).    

At this point I see the following options:
* I can post a PR to the fork of @gerryai. Though my changes are quite significant (in that some stuff gets deleted) and I'm not sure the code there is being maintained at all any more. I am thinking to open an issue in gerryai's repository for this as well, but wanted to first ask you as the author.
* You may want to revive the old version of your code, maybe under a different name, for which I'd be happy to send you a PR to whichever repository you choose.
* I can re-publish your code (as it is in my fork now), of course keeping the license of your choice and referencing your name, explaining that this is a copy of an old version of PDDL4J. In this case I'd be getting possible issues, questions etc. and you wouldn't have to look after the repository. I'm happy to do this.

It will be great if you let me know which solution you'd prefer, or if you have any other suggestions on how to go about this.

Best regards
Jennifer

**Comment by pellierd** [comment]
Dear Jennifer, 

I will not maintain the old code and it is not mergeable with the new one.  The code of the first version of PDDL4J is  always available to [sourceforge](https://sourceforge.net/projects/pdd4j/). It will be great to republish the original code and your new changes into the same repository.

 I suggest you to use the same licence (LGPL) as the new version of PDDL4J.

Please make a link to the current version of PDDL4J and enjoy.

Best regards, 

Damien

**Comment by JenniferBuehler** [comment]
Hi Damien,

I completely understand that, I wouldn't normally opt to maintain some of my old code either. I've looked into using your new version as well, but that would mean many changes in my code as I'm heavily using ``Exp`` and ``Substitution``.    
I'm happy to provide the code on my github and do the maintenance jobs, and I will make clear that it's an older version of pddl4j, so people know where the code comes from even without looking at the source.

Yes I saw it on sourceforge as well.  If I remember correctly, it's the same code as on github (I may have done a diff back then but I can't remember)?

So if I understand it correctly, you would like to have both the old and the new version in the same repository - so if I make a new repo on github, I could create two directories in it, ``pddl4j-v1`` and ``pddl4j-v1-modified`` (or something like that), and put the two versions in there. Is that what you mean?

I agree about changing the license over to the more common LGPL. I will make all the changes in the file headers accordingly.

Another thing to think about would be the name of the repository. ``pddl4j`` would be the same name as your new version, but the two versions are quite different, so it would be nice to reflect that in the name to avoid confusion. Of course while still explaining that it's an older version of pddl4j in the README. How about ``jPDDL`` or ``jpddl``? Or would you prefer to just stick to ``pddl4j``, or maybe modify it to ``pddl4j-v1`` (though it's a bit cumbersome with the version in the name)...

Kind regards
Jennifer

**Comment by pellierd** [comment]
Be free to use as you wish.

Damien
