### ISSUE TITLE
Unexpected "("

### ISSUE THREAD

**Issue by ckristhoff** [pellierd/pddl4j#19]
Hi
I have the next problem definition:

> (define (problem xss_problem)
(:domain XSS_ACTIONS)
(:objects firewall email_server - security_device global_risk0 - global_risk 
risk0 - risk 
threshold0 - threshold 
type_xss0 - type_xss)
(:init
(available firewall)
(available email_server)
(not (available_block_action))
(not (available_send_email_action))
(high_risk risk0)
(low_global_risk global_risk0)
(medium_threshold threshold0)
(persistent type_xss0)
)
(:goal
(or (= risk0 threshold0) (low_risk risk0) (note_risk risk0)))
)

but when I run the program it responses with unexpected "(" error 
I tried change or clausule to and clausule but the program responses with null pointer exception 
what's wrong with my problem?
The program shows the unexpected "(" exactly at initial parenthesis of goal

Edit: aditional info

**Comment by pellierd** [comment]
You have to specify the requirement with the key word :requirements for your problem. Your problem needs the following requirements:
- typing
- disjonctive preconditions 
- negative preconditions
or just adl. 

By default, just strips fragment of PDDL is allowed by the parser.

**Comment by ckristhoff** [comment]
I have the domain defined with typing and actions like next:

> (define (domain xss_actions)
  (:requirements :strips :typing :equality :adl)
  (:types security_device type_xss risk global_risk threshold - object)
  (:predicates (available ?x - security_device)
	       (critical_risk ?x - risk)
	       (high_risk ?x - risk)
	       (medium_risk ?x - risk)
               (low_risk ?x - risk)
	       (note_risk ?x - risk)
	       (critical_global_risk ?x - global_risk)
	       (high_global_risk ?x - global_risk)
	       (medium_global_risk ?x - global_risk)
	       (low_global_risk ?x - global_risk)
	       (note_global_risk ?x - global_risk)
	       (note_threshold ?x - threshold)
	       (low_threshold ?x - threshold)
	       (medium_threshold ?x - threshold)
	       (high_threshold ?x - threshold)
	       (critical_threshold ?x - threshold)
	       (persistent ?x - type_xss)
	       (no_persistent ?x - type_xss)
	       (available_block_action)
	       (available_send_email_action)
	       (available_send_sms_action)
	       (available_add_signature_action)
	       (available_redirect_action)
  )


  (:action Block
   :parameters (?r - risk)
   :precondition (and (available_block_action))
   :effect (and (low_risk ?r) (not (available_block_action)))
  )

  (:action Redirect
   :parameters (?r - risk)
   :precondition (and (available_redirect_action))
   :effect (and (low_risk ?r) (not (available_redirect_action)))
  )

  (:action Send_email
   :parameters (?r - risk)
   :precondition (and (available_send_email_action))
   :effect (and (low_risk ?r) (not (available_send_email_action)))
  )

  (:action Send_sms
   :parameters (?r - risk)
   :precondition (and (available_send_sms_action))
   :effect (and (low_risk ?r) (not (available_send_sms_action)))
  )

  (:action Add_signature
   :parameters (?r - risk)
   :precondition (and (available_add_signature_action))
   :effect (and (low_risk ?r) (not (available_add_signature_action)))
  )

  (:action AI_1
   :parameters (?f - security_device ?r - risk ?t - threshold ?rg - global_risk ?tx - type_xss)
   :precondition (and (available ?f) (persistent ?tx) (note_risk ?r) (note_global_risk ?rg) (note_threshold ?t))
   :effect (and (available_send_email_action))
  )

  (:action AI_2
   :parameters (?f - security_device ?r - risk ?t - threshold ?rg - global_risk ?tx - type_xss)
   :precondition (and (available ?f) (no_persistent ?tx) (note_risk ?r) (note_global_risk ?rg) (note_threshold ?t))
   :effect (and (available_send_email_action))
  )

  (:action AI_3
   :parameters (?f - security_device ?r - risk ?t - threshold ?rg - global_risk ?tx - type_xss)
   :precondition (and (available ?f) (persistent ?tx) (low_risk ?r) (note_global_risk ?rg) (note_threshold ?t))
   :effect (and (available_block_action) (available_add_signature_action) (available_send_email_action))
  )

250 actions more...

**Comment by pellierd** [comment]
1. There was a bug in the pre-instantiation process when negative fact are defined in the initial state.  The bug is fixed in the devel branch that produce the null pointer exception.
2. In the goal of your problem you write  "(= risk0 threshold0)", it does not make sens. It will be automatically simplified and replaced by false.

**Comment by ckristhoff** [comment]
thank you so much @pellierd 
all works perfect.
