### ISSUE TITLE
1. problem file Constraints is NULL if it contains a preference (within t φ)  2. (always-within tφψ) is not handled correctly maybe

### ISSUE THREAD

**Issue by mobab** [pellierd/pddl4j#2]
Greetings,
Kindly note the attachment as it contains three files: domain, problem, and plan
According to the BNF grammar of PDDL3.0, the input problem and domain are correct. (tested also using lpg-syntax) and OPTIC Planner generates a sound plan (also in the attachment).

```
String dir = "./././directory/";
String f_domain = dir + "domain.pddl";
String f_problem = dir + "problem.pddl";
Parser parser = new Parser();
try 
{
	parser.parse(f_domain, f_problem);
} 
catch (FileNotFoundException e) 
{
}
if (!parser.getErrorManager().isEmpty()) 
{
	parser.getErrorManager().printAll();
	System.exit(0);
}
Domain domain = parser.getDomain();
Problem problem = parser.getProblem();
```
No errors are shown by the Error manager, However if i try:
1- Exp myConstraints = problem.getConstraints(); // this returns null
or
2- put a breakpoint near the final line (shown above in the code section) "Problem problem = parser.getProblem();", then debug and navigate to see the problem variable, the constraints field is NULL

It should contain all the things i have in the constraints section in the problem file (in the attachment).

After running some tests, 
i found out two issues:
1-  The preference **within** is causing the whole constraints object to be null
`(preference b4 (within 72 (in p1 street4))) `
2- The preference **always-within** 
`(preference b8 (always-within 25 (in p1 street1)(in p1 street2)))`
is considered and showed by PDDL4J as (sometime-before 25.0 (in p1 street1))) and i think this is not correct.
Thanks for your time and efforts.
Sincere regards

[domain.txt](https://github.com/pellierd/pddl4j/files/135198/domain.txt)
[plan.txt](https://github.com/pellierd/pddl4j/files/135199/plan.txt)
[problem.txt](https://github.com/pellierd/pddl4j/files/135200/problem.txt)

**Comment by mobab** [comment]
the bug for the within was a typo mistake in the function Exp within_con_gd() 
```
  final public Exp within_con_gd() throws ParseException {
        Exp conGD = new Exp(Connective.WITHIN);
        Token toekn = null;
        Exp node = null;
    left_bracket();
    jj_consume_token(WITHIN);
    token = jj_consume_token(NUMBER);
    node = node();
    right_bracket();
                Exp n1 = new Exp(Connective.NUMBER);
                n1.setValue(Double.parseDouble(token.image));
                conGD.addChild(n1);
                conGD.addChild(node);
                {if (true) return conGD;}
    throw new Error("Missing return statement in function");
  }
```
replacing the word toekn with token solved the problem for within.

**Comment by pellierd** [comment]
1. There is a bug when reading the within expression by the lexer. Variable "toeken" is declared but "token" is used. It is strange because this code is generated by javacc without error. Whatever, the lexer.jj file was modified to fix the bug. The bug is fixed in the devel branch.
2. There is a bug when reading the always-within expression by the lexer. The lexer sets a wrong connective to this expression (sometime-before instead of always_within). The bug is fixed in the devel branch.
