### ISSUE TITLE
empty precondition

### ISSUE THREAD

**Issue by DamKoVosh** [pellierd/pddl4j#20]
Hello Damien,

When using Actions with empty preconditions, which as far as my rather limited understanding of pddl is allowed, i get problems with your parser. "expected ':precondition ...'"
Would it be possible to support empty preconditions?

Best regards 
Richard

**Comment by pellierd** [comment]
You can define an action with empty precondition. You can use the following syntaxe:
- :precondition () 
- :precondition (and )

If it doe not work, please send me the input domain and problem.

**Comment by DamKoVosh** [comment]
hmm you are right. But why do i have to set the precondition at all in that case?

**Comment by pellierd** [comment]
It is the PDDL syntax. See https://helios.hud.ac.uk/scommv/IPC-14/repository/kovacs-pddl-3.1-2011.pdf for more details.

**Comment by DamKoVosh** [comment]
well the resource is not on the adress you pasted, at least its telling me so, but the 2 defs i found for 3.1 has: <action-def body> ::= [:precondition <emptyOr (pre-GD)>]
[:effect <emptyOr (effect)>]
and if im not completly mistaken "[...]" means that something is optional, doesn't it?

**Comment by pellierd** [comment]
The rule <action-def body> implemented in PDDL4J is :
<action-def body> ::= :precondition <emptyOr (pre-GD)>
                                      :effect <emptyOr (effect)>

The key word :precondition and :effect are required even if the precondition and the effect are empty.  I never see action definitions without these key words in any planning domains and problem from IPC.

If you have time, you can propose a PDDL BNF for PDDL4J. It would help to clarify some narrow points of the syntax.
