### ISSUE TITLE
toString spacing

### ISSUE THREAD

**Issue by DamKoVosh** [pellierd/pddl4j#21]
Hello Damien,
another small thing. 
When using the toString() of the domain there is no spacing before the :action, :preconditon and :effect. It may not be of much importance, but pasting a in pddl4j stored domain to some planners fail due to this spacing.
Would be nice if a spacing could be inserted at this positions.

Best regards
Richard

**Comment by pellierd** [comment]
The problem occurs when you print an object Domain or an object CodedProblem ?

**Comment by DamKoVosh** [comment]
http://planning.domains/ implemented planner internal referred as siw-then-bfsf throws a parsing error, still seems to be able to do its job. Temporal fast downward planner, is unable to work with it at all.

**Comment by pellierd** [comment]
This point is not well defined in the PDDLJ syntax.

**Comment by DamKoVosh** [comment]
yes I agree, there is no definition for that, and i as well have already encountered solvers, that are really cranky, when fed with whitespace. one space did not produce any errors with the solvers i encountered so far, but that does't mean there are such solvers our there.
I understand if you leave it like it is. With a simple replace() the spaces can be included anyways.
