### ISSUE TITLE
(= (function) X) in init

### ISSUE THREAD

**Issue by DamKoVosh** [pellierd/pddl4j#23]
Hello again,
for some reason, a Term (= (<basic-function-term>) <number>) in init, has the wrong connective i gues. 
FN_ATOM instead of EQUAL.
which in turn scews up the equals method.
I gues thats a bug? Or is a there a special reason for that?

sincerely
Richard

**Comment by pellierd** [comment]
Could you give me the intput domain and problem to reproduce the bug ?

**Comment by DamKoVosh** [comment]
Well that is a valid decision I guess. I would still expect the equals method to match them both as equal in that case. On the other hand, it is a different structure so maybe the equals method should act as it does. Strange to have two different structures for the same thing, or not?

**Comment by pellierd** [comment]
It the same object (Exp) with a different connective.

**Comment by DamKoVosh** [comment]
You are right, following the def its not a <binary-comp> in the init section, so your behaviour is correct.
