### ISSUE TITLE
parse request via string

### ISSUE THREAD

**Issue by DamKoVosh** [pellierd/pddl4j#24]
Hi again,
This is not really an issue, but a feature request.
At the moment, if I didn't oversee some functionality it is only possible to parse extern files. If i have already loaded the pddl file to my program for whatever reason, then i have to write it back to the file to use your parser.
Id be interested in a direct String input, maybe even for parts of the pddl say only parsing one action. Not sure if that is possible with your architecture however.

Kind regards Richard

**Comment by pellierd** [comment]
For the moment, it is not possible to read a domain or a problem directly form an input stream. 
It could be useful. I will add this feature in the devel branch as soon as possible.

**Comment by DamKoVosh** [comment]
Hi, are there any updates on this feature so far?

**Comment by ehermellin** [comment]
Hi, 
There is a new release of PDDL4J (v3.6.0). It's is now possible to parse a string containing a pddl domain and/or problem with the *parseFromString* method.
Best regards, 
Emmanuel.
