### ISSUE TITLE
Class cannot be resolved

### ISSUE THREAD

**Issue by ELHAMLAOUI** [pellierd/pddl4j#25]
Hi Damien,
Im trying to use pddl4j in eclipse but im getting the following errors:
fr.uga.pddl4j.parser.lexer.Token cannot be resolved
fr.uga.pddl4j.parser.lexer.ParseException cannot be resolved
Is there a missing package ?
Thanks in advance

**Comment by pellierd** [comment]
You don't generate the classes of the lexer with javacc. 
To compile and generate the lexer classes please use gradle. 
I suppose it exists a plugin for eclipse.
