### ISSUE TITLE
other Planners

### ISSUE THREAD

**Issue by onetarik** [pellierd/pddl4j#26]
Hi Damien,
Is there is other planners (for example Graphplan) or how can i add a planner to PDDL4J
Thanks in advance

**Comment by pellierd** [comment]
For the moment there is only the planner called HSP with different relaxation heuristics available in the master branch. 

A simple implementation of FastForward is also available in a specific branch written by one of my master student. I didn't test it for the moment.  I will merge it as soon as possible.

If you are looking for a graphplan implementation. Have a look to the first version of the library on sourceforce, a graphplan implementation is available. I have not yet found enough time to add this implementation in the new version of the library.

Now if you wish to implement your own planner or propose an implementation of an existing planner to pddl4j fill free. Parse a domain and a problem and then encode the planning problem into a CodedProblem classe. All you need to write your own planner is in this classe. Have a look to the   [section Getting Started](https://github.com/pellierd/pddl4j/wiki/Getting-Started) the wiki page.

**Comment by pellierd** [comment]
A simple version of FastForward was added in the devel branch. Other planners will follow.

**Comment by ehermellin** [comment]
Hi, 
There is a new release of PDDL4J (v3.6.0). In this release, you can find two new planners : Fast Forward and Enforced Hill Climbing.
It is planned to add graphplan later.
Best regards, 
Emmanuel.
