### ISSUE TITLE
Problem while parsing actions

### ISSUE THREAD

**Issue by bellerifabio** [pellierd/pddl4j#27]
Hi,
I'm trying to parse a domain with 6 :durative-actions, but when I pass the file to the Parser, it reads only the first action.
Can you help me?

**Comment by bellerifabio** [comment]
I might have understood what's the problem: I noticed that if an operator has a negative precondition, the Parser skips the entire action.

**Comment by bellerifabio** [comment]
I might have understood what's the problem: I noticed that if an operator has a negative precondition, the Parser skips the entire action.

**Comment by pellierd** [comment]
You may add :negative-precondition in the requirement before parsing.
To enable us to reproduce your problem, give us your domain and your problem.
