### ISSUE TITLE
possible bug when the goal section in the problem file is empty

### ISSUE THREAD

**Issue by mobab** [pellierd/pddl4j#3]
There is a problem if a problem file has no goals, and has one or more preferences
Kindly note the attached files for an example of such scenario, the plan is generated by OPTIC planner.
```
String dir = "./././directory/";String dir = "./././directory/";
String f_domain = dir + "domain.pddl";
String f_problem = dir + "problem.pddl";
Parser parser = new Parser();
try 
{
    parser.parse(f_domain, f_problem);
} 
catch (FileNotFoundException e) 
{
}
if (!parser.getErrorManager().isEmpty()) 
{
    parser.getErrorManager().printAll();
    System.exit(0);
}
Domain domain = parser.getDomain();
Problem problem = parser.getProblem();
Exp goal = problem.getGoal();
System.out.println(goal);
```

we will get an UncaughtException 

if we debug and check out the object goal in  **Exp goal = problem.getGoal();** mentioned in the code above, we will find that there is something wrong with it, and also the variable problem it self
will have the msg: com.sun.jdi.InvocationException occurred invoking method.

Thanks for your time and efforts
Sincere regards.
[domain.txt](https://github.com/pellierd/pddl4j/files/136409/domain.txt)
[plan.txt](https://github.com/pellierd/pddl4j/files/136407/plan.txt)
[problem.txt](https://github.com/pellierd/pddl4j/files/136408/problem.txt)

**Comment by pellierd** [comment]
The problem comes from the toString() method of the class Exp. It does not take into account the fact that AND expressions could be empty. The bug was fixed in the devel branch.
