### ISSUE TITLE
Problem running using JDK 9.0.4

### ISSUE THREAD

**Issue by ggirotto** [pellierd/pddl4j#38]
I'm facing a bug when trying to use the library with the latest version of jdk (9.0.4 today). I've tried to execute the library and got the following error

<img width="1079" alt="screen shot 2018-04-04 at 9 16 13 am" src="https://user-images.githubusercontent.com/11745745/38307062-e08fb4c6-37e8-11e8-92e3-96d62422ec61.png">

I've downgraded the Java version and it started working perfectly, so it may be a bug caused by the new modifications that were introduced in this new jdk version.

**Comment by ehermellin** [comment]
Hi@ggirotto, 
Thanks you for using PDDL4J and for reporting this problem with Java 9. I will investigate this issue as soon as possible.
Best regards,
Emmanuel.

**Comment by ehermellin** [comment]
Hi @ggirotto,
As "Java SE 9 has reached end of support", you can use Java JDK 10.0.1. 
The latest version of PDDL4J (3.7.0) works perfectly with Java 10.
Best regards, 
Emmanuel.
