### ISSUE TITLE
Consider publishing to maven central

### ISSUE THREAD

**Issue by arthur-bit-monnot** [pellierd/pddl4j#52]
Hi, thanks for making pddl4j available it has been a really helpful toolbox for me.

It would be great if stable releases of PDDL4J were published to maven central to enable better integration with the rest of the ecosystem. This is especially important when managing (transitive) dependencies on pddl4j and would greatly facilitate its usage and adoption.

**Comment by ehermellin** [comment]
Hi Arthur, 

First, we want to thank you for using PDDL4J.

It is true that publishing PDDL4J to maven central would be very intersting even for us (webapps, gui, etc.). It was not one of our current priorities, but I will try to see if it can be done in the coming weeks. I will notify in this thread when the publishment will be made.

Best regards, 

Emmanuel.

**Comment by arthur-bit-monnot** [comment]
Sounds good to me. Thank you.

**Comment by ehermellin** [comment]
Hi Arthur, 

You can find PDDL4J on Maven : https://search.maven.org/artifact/com.github.pellierd/pddl4j/3.7.2/pom

Best regards,

Emmanuel.
