### ISSUE TITLE
PDDL4J web application not working

### ISSUE THREAD

**Issue by sjzgqtyzjy** [pellierd/pddl4j#53]
Seems that the web application is not giving any result now. No matter what domain and problem file you put in, it always displays NO PROBLEM TO SOLVE. First I was using my own files (they are fine with editor.planning.domains). I thought it was my files' issue, but then I switched to example pddl files provided by this GitHub pddl4j website, and it still displays "No problem to solve".

![image](https://user-images.githubusercontent.com/33207488/46818364-9d7f3600-cdb3-11e8-9004-4093b7426bf1.png)

Is this issue happening because I'm not using it correctly? Or something wrong is going on? Hope it can be solved. Thanks!

**Comment by ehermellin** [comment]
Hi!

I am sorry about this problem. But, i'm trying the webapps this morning with pddl files available on the github and everything seem good (see picture).

![test_pddl4j](https://user-images.githubusercontent.com/7964512/46855468-160de300-ce04-11e8-993c-6cf3eda88dc6.png)

Can you give us more informations? Do you use the "Find solution" button after selecting files?

Best regards, 

Emmanuel.

**Comment by sjzgqtyzjy** [comment]
Yes, I click "Find solution" only after I have selected files like this:
![image](https://user-images.githubusercontent.com/33207488/46856318-aa923880-ce38-11e8-93b7-565f2df5b255.png)

Unfortunately, this problem persists in my place. I was thinking that it could be my computer's individual problem, so I deliberately switched to another computer and another Internet connection, and this problem is still there.

I have no idea what causes the problem. Is it relevant to the OS we use? Recently I have no Linux/MacOS machines in my hands, the two machines I used have Win10 and Win7, respectively.

**Comment by ehermellin** [comment]
When you use the webapps, the files are sent to a tomcat server on Debian 9 running the pddl4j library. So the OS on your computer should not be a problem. But maybe the files have been changed by your computer when you download them (because you seems to live in an Asian country). So can you send us these files: emmanuel.hermellin@univ-grenoble-alpes.fr

**Comment by pellierd** [comment]
PDDL4J web application not more supported.
