### ISSUE TITLE
com.sun.jdi.InvocationException occurred invoking method

### ISSUE THREAD

**Issue by mobab** [pellierd/pddl4j#6]
Greetings,
```
Exp effect = new Exp(Connective.AND); // or other connectives e.g., Connective.AT_START
System.out.println(effect); 
```
When debugging effect will contain the msg : com.sun.jdi.InvocationException occurred invoking method
I think there might be something wrong in the toString() method of the Exp Class, according to stackoverflow website:
The root cause is that when debugging the java debug interface will call the toString() of your class to show the class information in the pop up box, so if the toString method is not defined correctly, this may happen.
This is causing further problems when creating an operator.
```
List<TypedSymbol> tempParameters = new LinkedList<TypedSymbol>();
Exp effects = new Exp(Connective.AND);
Exp preconds = new Exp(Connective.AND);
Op op = new Op(new Symbol(Kind.ACTION, "DummyAction"), tempParameters, preconds, effects);
System.out.println(tempOp);
```
Sincere regards

**Comment by pellierd** [comment]
I check your code on the devel branch but no InvocationException is thrown.
Try to rebuild the project and assemble a new the jar of the library.

**Comment by miquelbofill** [comment]
It seems that object-fluents do not parse correctly. I attach a toy PDDL domain file to check it.
[object-fluents.txt](https://github.com/pellierd/pddl4j/files/206713/object-fluents.txt)

Many thanks for your work!
