### ISSUE TITLE
Test not completing

### ISSUE THREAD

**Issue by zacharywhitley** [pellierd/pddl4j#60]
FFAnytimeTest is not completing or is taking a very long time. 

<==========---> 81% EXECUTING [15m 43s]
> :test > 84 tests completeduga.pddl4j.test.planners.statespace.ff.FFAnytimeTest
> :test > Executing test fr.uga.pddl4j.test.planners.statespace.ff.FFAnytimeTest

**Comment by zacharywhitley** [comment]
Seems to be making progress. I ran it again and am now at 104 tests completed, even thought the progress bar is still at 81%. I guess they're just long running.

**Comment by pellierd** [comment]
It can be long. It tries to test all the first problems of all the International Planning Competition.

**Comment by ehermellin** [comment]
Hi,
The JUnit process run during 1 hour and 45 minutes approximatively.
You can build PDDL4J with the noTest flag to avoir this step or just build the jar file.

**Comment by zacharywhitley** [comment]
I'll try to be a little more patient then :)  Thanks for the cool package. I was unfamiliar with PDDL until recently and I'm interested to see what I can do with it. The first thing that came to mind was using it for generating plans for building cloud infrastructure. Something like a smarter [terraform](https://www.terraform.io/)
