### ISSUE TITLE
Include fluents in requirements leads to "problem to encode is not ADL"

### ISSUE THREAD

**Issue by padmalcom** [pellierd/pddl4j#66]
Hi, first of all thank you for your great library! I have a working domain with a solvable problem. When I add fluents to the list of requirements, I get an error and cannot really explain why.

The error I get is:
> the problem to encode is not ADL, ":requirements" not supported at this time

When I remove the fluent requirement the domain file can be parsed. But of course, I'd like to use it so I'm creating the issue.

By the way: I receive the info that the domain file and the problem file are parsed successfully.

**Comment by padmalcom** [comment]
Found out that action-costs is accepted. When I move on to object-fluents, I receive the same error as shown in the original post.

It somehow feels like I'm generally doing sth wrong. I use the newest version of your library (3.8.3).

**Comment by pellierd** [comment]
The parser accepts PDDL3.1. The planners implemented only ADL +  cost action.
Please see the documentation.
