### ISSUE TITLE
"the problem to encode is not ADL, ":requirements" not supported at this time" ?

### ISSUE THREAD

**Issue by ko56** [pellierd/pddl4j#67]
Hello, I am a beginning user of pddl4j.  I am trying to model finding paths in a graph.
I attach my domain and problem files, gd.pddl and gp.pddl.

But I am getting the error message in the title.  Am I doing something wrong?

[gd.pddl.gz](https://github.com/pellierd/pddl4j/files/3602109/gd.pddl.gz)
[gp.pddl.gz](https://github.com/pellierd/pddl4j/files/3602110/gp.pddl.gz)

**Comment by pellierd** [comment]
:derived-predicates is not implemented at this time in PDDL4J.
