### ISSUE TITLE
Can action costs and  ":metric" be used in order to maximize/minimize the costs

### ISSUE THREAD

**Issue by bmainz** [pellierd/pddl4j#68]
Hi,

I have the following domain and problem:

[problem.txt](https://github.com/pellierd/pddl4j/files/3604317/problem.txt)
[gripper.txt](https://github.com/pellierd/pddl4j/files/3604318/gripper.txt)

I try to minimize the costs. However, the result is always not even close to the minimum. Changing the strategy helps a little but it still seems to ignore the metric. When I set the metric to 'maximize' the planner still minimizes the costs.

Is there anything I miss here? Or is metric not implemented yet, but can be parsed?

Thanks!

**Comment by pellierd** [comment]
Metric is not implement just cost-action with minimization of the cost of the plan.
