### ISSUE TITLE
"the problem to encode is not ADL, ":requirements" not supported at this time" -- maybe related to numeric computation? 

### ISSUE THREAD

**Issue by violetbingzhe** [pellierd/pddl4j#69]
Hello, I encountered the error ":the problem to encode is not ADL, ":requirements" not supported at this time”, I am wondering if it’s because PDDL4J is not supporting numeric planning/do not have built-in numeric planner. 

Here's the domain pddl: 

> (define (domain test)
> (:requirements :typing :numeric-fluents :equality)
> (:types server - object)
> 
> 
>   (:functions 
>        (label ?p - server)
>        (number_of_pod ?p - server) - number)
> 
>   (:action setNum
>     :parameters (?p - server)
>     :precondition ()
>     :effect (increase (number_of_pod ?p) 1)
>     )
> )

Here's the problem pddl:

> (define (problem p0) (:domain test)
> (:objects
> 		frontend master - server)
> 
> (:init
> 	(= (number_of_pod master) 0)
> 	(= (number_of_pod frontend) 0)
> 
> )
> 
> (:goal (and (= (number_of_pod master) 1)
> 			(= (number_of_pod frontend) 3)
> 		))
> 
> )

Thanks a lot!

**Comment by pellierd** [comment]
Just ADL with cost action are implemented.
