### ISSUE TITLE
The document says that HTN is supported after 3.8.1, but syntax error is reported

### ISSUE THREAD

**Issue by xiaozw123** [pellierd/pddl4j#70]
The document says that HTN is supported after 3.8.1, but syntax error is reported
(defdomain UnmannedCombatVehicle
(
(:operator ( !operator-move  ?parameter-agent  ?parameter-from  ?parameter-to )
((  predicate-next ?parameter-from  ?parameter-to  ) ) 
((  predicate-at ?parameter-agent  ?parameter-from ) ) 
((  predicate-at ?parameter-agent  ?parameter-to  ) ) 
) 

(:operator ( !operator-fire  ?parameter-target )
() 
( (  predicate-at ?parameter-target  ?parameter-to  )) 
() 
)
 
(:operator ( !operator-evaluate  ?parameter-target )
() 
() 
() 
)

(:operator ( !operator-report  ?parameter-target )
() 
() 
() 
)

(:operator ( !operator-troubleshoot  ?parameter-barrier )
() 
() 
() 
)

(:operator ( !operator-hidden  ?parameter-agent ?parameter-position)
()
() 
() 
)

(:method ( method-pursuitPosition  ?parameter-agent  ?parameter-from  ?parameter-to )
(  (  predicate-at ?parameter-agent  ?parameter-from  )
   (  predicate-next ?parameter-from  ?parameter-to  ) )
 ( (  !operator-move ?parameter-agent  ?parameter-from  ?parameter-to  ))
 (  (  predicate-at ?parameter-agent  ?parameter-from  )
    (  predicate-next ?parameter-from  ?parameter-x  ))
 (  (  !operator-move ?parameter-agent  ?parameter-from  ?parameter-x  )
    (  method-pursuitPosition ?parameter-agent  ?parameter-x  ?parameter-to  ))
 )

(:method ( method-attract ?parameter-agent ?parameter-from ?parameter-target ?parameter-to)
 (  (predicate-at ?parameter-agent  ?parameter-from)
    (predicate-at ?parameter-target  ?parameter-to))
 (  (method-pursuitPosition  ?parameter-agent  ?parameter-from  ?parameter-to)
    ( !operator-fire  ?parameter-target )
	( !operator-evaluate  ?parameter-target )
	( !operator-report  ?parameter-target )
	
	))	
(:method ( method-troubleshoot ?parameter-agent ?parameter-from ?parameter-barrier ?parameter-target ?parameter-to)
 (  (predicate-at ?parameter-agent  ?parameter-from)
    (predicate-at ?parameter-target  ?parameter-to))
 (  (!operator-troubleshoot ?parameter-barrier)
    (method-pursuitPosition  ?parameter-agent  ?parameter-from  ?parameter-to)
    ( !operator-fire  ?parameter-target )
	( !operator-evaluate  ?parameter-target )
	( !operator-report  ?parameter-target )
	
	))

(:method ( method-hidden  ?parameter-agent ?parameter-position)
 ()
 ((!operator-hidden ?parameter-agent ?parameter-position)
	))
))

**Comment by pellierd** [comment]
HTN syntax is supported but no HTN SHOP syntax. Have a look to the file lever.jj to have a complete view of the syntax accepted in 3.8.1. 

In addition, in view of the various works in progress in the HTN community, the HTN language that will be accepted will be HDDL see :
https://lig-membres.imag.fr/PPerso/membres/pellier/lib/exe/fetch.php?media=publications:pellier19d.pdf
The HDDL language will be supported soon. 

Warning it is not because the HTN syntax is supported does not mean that a HTN planner is available in PDDL4J.

**Comment by xiaozw123** [comment]
okay, thank you

**Comment by pellierd** [comment]
HDDL syntax is now supported by the parser. 

At this time no HTN planner is available into the library. We are working on.

**Comment by xiaozw123** [comment]
Thank you very much for supporting HTN
