### ISSUE TITLE
How to generate new problem with domain, old problem and actions?

### ISSUE THREAD

**Issue by SeanWangDev** [pellierd/pddl4j#71]
Hi,

Normally we use domain and problem files to plan for solutions.

Assume we've got a solution with 3 actions (actionA, actionB, actionC), and now actionA is done.

Somehow the environment changes, makes us want a re-plan for the actions remains to be done, e.g. actionB and actionC.
One way to do re-plan is 

1. generate a new problem with the original problem and actions already taken(actionA). 
2. And let the new problem (also updated with changed facts for environment changes), run with the original domain, which should then give new solution.

Is this the correct way of thinking about the re-plan a partially done problem?
Are there any ways to generate a new problem with actions and original problem and domain?

Thanks.

**Comment by pellierd** [comment]
You can add action to a coded problem directly but it is difficult to add fluent to the coded problem. 

I think that it better to generate a PDDL file by using the to string method of a coded problem and and encode the new problem.

**Comment by SeanWangDev** [comment]
Hi @pellierd,
Thanks for your reply. 

> You can add actions to a coded problem directly but it is difficult to add fluents to the coded problem because you have to change also the size of the bitsets of the actions.

If I get it right, adding actions and adding fluents are two things that correlate with each other.  
What kinds of fluents are we talking about? Is it possible that we can add already-happened actions without adding fluents?

**Comment by pellierd** [comment]
We call fluents the propositions used in the preconditions and the effects of the actions.
