### ISSUE TITLE
Mismatches in Timeout Specification

### ISSUE THREAD

**Issue by faizan-m** [pellierd/pddl4j#72]
In Planner.java, timeout is said to be specified in Seconds

https://github.com/pellierd/pddl4j/blob/405b12ed212b45e0f5439b1a0bd131c83a2fba71/src/main/java/fr/uga/pddl4j/planners/Planner.java#L66

However, in actual implementations, the values used are milliseconds:
https://github.com/pellierd/pddl4j/blob/405b12ed212b45e0f5439b1a0bd131c83a2fba71/src/main/java/fr/uga/pddl4j/planners/statespace/search/strategy/BreadthFirstSearch.java#L114

Similar discrepancies exist in a couple other places too.

**Comment by pellierd** [comment]
The timeout is given as input from the command line in second. However time is measured in milliseconds by the planner.
