### ISSUE TITLE
Benchmark problem and domain descriptions missing

### ISSUE THREAD

**Issue by fjulian** [pellierd/pddl4j#84]
The paper "From Classical to Hierarchical: benchmarks for the HTN Track of the International Planning Competition" mentions that the domains presented in the paper are available as part of the PDDL4J library. Unfortunately, this repo's github page I could not find most of them. They are referenced in the file [src/test/resources/validatePlan.sh](https://github.com/pellierd/pddl4j/blob/405b12ed212b45e0f5439b1a0bd131c83a2fba71/src/test/resources/validatePlan.sh), but the referred paths (e.g. benchmarks/ipc8/childsnack) do not exist in the repository, neither on "master" nor on any other branch.

In the mean time, I found the benchmarks in [this other repo](https://github.com/panda-planner-dev/ipc2020-domains). To be consistent with the paper, the domains could be added to the PDDL4J repo as well, or a link to the other repo could be added to PDDL4J's readme to save future readers of the paper the effort of having to search for the domains.

**Comment by pellierd** [comment]
The HTN problem and the domain descriptions are only available for the moment in the [devel branch] (https://github.com/pellierd/pddl4j/tree/devel/src/test/resources/benchmarks/hddl/ipc2020)

The domains and the problems will be pushed soon in the master branch.
