### ISSUE TITLE
Documentation example does not work: no function `setDomain` on planner objects

### ISSUE THREAD

**Issue by victorpaleologue** [pellierd/pddl4j#86]
Hello,
I am trying out [this example from the documentation](http://pddl4j.imag.fr/configuring_planners_by_programming.html#step-1-create-a-simple-java-project-with-pddl4j).
But I am stuck when I write:
```java
planner.setDomain(benchmarks + "domain.pddl");
```
Because there is no such function `setDomain`.

**Comment by pellierd** [comment]
The code of documentation the for a version 4.0.0 is only available for the moment in the devel branch. 
Thus if you want to use this documentation, clone the devel branch.

**Comment by victorpaleologue** [comment]
Can I find the documentation for the version 3.8, instead?

**Comment by pellierd** [comment]
[All the version of the api documentation](http://pddl4j.imag.fr/api_documentation.html) are available online.
