### ISSUE TITLE
Log4j vulnerability in dependencies

### ISSUE THREAD

**Issue by claj** [pellierd/pddl4j#94]
The current version 3.8.3 has a dependency on vulnerable versions of log4j

https://mvnrepository.com/artifact/com.github.pellierd/pddl4j/3.8.3

The most recent version, log4j 2.19.0 currently has no known vulnerabilities

https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-core/2.19.0

An upgrade to log4j 2.19.0 would resolve these CVEs.

**Comment by pellierd** [comment]
The new version of the library (4.0) will integrate the latest version of log4j. It will be pushed to the master branch soon. If you want to use it, clone the devel branch.

**Comment by pellierd** [comment]
Log4J has been updated to version 4.0.0 available on master.
