### ISSUE TITLE
[HDDL] - parser stops on encountering dummy action (warning)

### ISSUE THREAD

**Issue by o-fir** [pellierd/pddl4j#98]
I am using the up-to-date library from devel branch.
When parser encounters a dummy noop action it stops.
Please make it so the parser doesn't stop, after this warning is displayed.

Running PDDL4J on **Childsnack** will result in:
```
Parser warning at line 60, column 10, file (C:\benchmarks\total-order\Childsnack\domain.hddl) : Action nop is always applicable: action preconditions can be simplified to TRUE.

Parser warning at line 62, column 17, file (C:\benchmarks\total-order\Childsnack\domain.hddl) : OR expression is empty.
```

nop action:
```
(:action nop
  :parameters ()
  :precondition ()
  :effect ())
```

**Comment by o-fir** [comment]
the warning is simply sent to ErrorManager. When getting a message via ErrorManager one should not automatically assume it;s an error

**Comment by pellierd** [comment]
Yes, it is just a warning. You can suppress warnings if you wish by telling it to the error manager.
