### ISSUE TITLE
PDDL parser lowers capital letters

### ISSUE THREAD

**Issue by tobiaswjohn** [pellierd/pddl4j#99]
I am using this library only to parse a PDDL problem file to extract the initial state. The predicate names in the problem file use lower and capital letters, as they are related to things outside the planning domain. However, if I use the parser, all letters become lower case (I do understand that this might be desired in general). Is there a way to configure the parser in such a way that the capital letters remain capital letters?

In case it is relevant: I am using the parser like this at the moment:
`parser.parseProblem(filePath);`
`p = parser.getProblem();`

**Comment by pellierd** [comment]
To make the parser case sensitive just change the option in the file [Lexer.jj](https://github.com/pellierd/pddl4j/blob/master/src/main/java/fr/uga/pddl4j/parser/lexer/Lexer.jj) ligne 22 
`IGNORE_CASE=true;` by `  IGNORE_CASE=false;` and rebuild the library.

**Comment by tobiaswjohn** [comment]
I tried your suggestion and it does not solves my issue. The capital letters are still converted to lower case.

**Comment by pellierd** [comment]
You right it is a bug. The previous proposition, i.e., change the option in the file [Lexer.jj](https://github.com/pellierd/pddl4j/blob/master/src/main/java/fr/uga/pddl4j/parser/lexer/Lexer.jj) ligne 22
IGNORE_CASE=true; by   IGNORE_CASE=false; and rebuild the library works.
